name: Pull Request Comment Action
description: An example custom action written in JavaScript
author: Abhishek Panda
inputs:
  owner:
    description: 'The owner of the repository (user or org)'
    required: true
  repo:
    description: 'The repository name'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: 'node16'
  main: action.js