name: Pull Request Comment Action
description: An example custom action written in JavaScript
author: Abhishek Panda
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: 'node16'
  main: action.js
  steps:
    - run: node ./.github/actions/add-pr-comment/action.js
      shell: bash