name: Add Pull Request Comment Action
description: An example custom action written in JavaScript
author: Abhishek Panda
inputs:
  input1:
    description: Description of input 1
    required: true
  input2:
    description: Description of input 2
    required: false
runs:
  using: node12
  main: action.js