name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [12.18.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run Javascript
        run: |
          node -e '
          // JavaScript code here
          const message = "Hello, GitHub Actions!";
          console.log(express)
          console.log(message);
          '