name: Update Pull Request Stats

on:
  pull_request:
    types:
      - opened

jobs:
  update_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Number
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Calculate Stats
        run: |
          # Calculate your stats here and store them in a variable
          STATS="Your stats: X"

          echo "STATS=${STATS}" >> $GITHUB_ENV

      - name: Update Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.PR_NUMBER;
            const stats = process.env.STATS;
            const comment = `Stats: ${stats}`;

            const { owner, repo } = context.repo;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment,
            });
