name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [12.18.0]
    runs-on: ${{ mattrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Commenting on PR with Binder link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
            var PR_HEAD_REF = process.env.PR_HEAD_REF;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${PR_HEAD_USERREPO}/${PR_HEAD_REF}) :point_left: Launch a binder notebook on branch _${PR_HEAD_USERREPO}/${PR_HEAD_REF}_`
            })
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}